class Products {
  final int id;
  final String name;
  final double price;
  final String description;
  final String image;
  final double stars;

  Products({
    required this.id,
    required this.name,
    required this.price,
    required this.description,
    required this.stars,
    required this.image,
  });
}

List<Products> homeProductsList = [
  Products(
    id: 1,
    name: 'Bag',
    stars: 1,
    image: 'assets/products/bag.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 2,
    name: 'Blender',
    stars: 1,
    image: 'assets/products/blender.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 3,
    name: 'Camera',
    stars: 1,
    image: 'assets/products/camera1.png',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 4,
    name: 'Wireless',
    stars: 1,
    image: 'assets/products/wireless.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 5,
    name: 'Watch',
    stars: 1,
    image: 'assets/products/watch2.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 6,
    name: 'Headphone',
    stars: 1,
    image: 'assets/products/Headphone.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 7,
    name: 'Makeup',
    stars: 1,
    image: 'assets/products/makeup.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 8,
    name: 'Mobile',
    stars: 1,
    image: 'assets/products/mobile.jpeg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 9,
    name: 'Shoe',
    stars: 1,
    image: 'assets/products/shoes.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 10,
    name: 'Smartwatch',
    stars: 1,
    image: 'assets/products/smartwatch.jpeg',
    description: 'abc',
    price: 100,
  ),
];
List<Products> watchesList = [
  Products(
    id: 1,
    name: 'Bag',
    stars: 1,
    image: 'assets/products/bag.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 2,
    name: 'Blender',
    stars: 1,
    image: 'assets/products/blender.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 3,
    name: 'Camera',
    stars: 1,
    image: 'assets/products/camera1.png',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 4,
    name: 'Wireless',
    stars: 1,
    image: 'assets/products/wireless.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 5,
    name: 'Watch',
    stars: 1,
    image: 'assets/products/watch2.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 6,
    name: 'Headphone',
    stars: 1,
    image: 'assets/products/Headphone.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 7,
    name: 'Makeup',
    stars: 1,
    image: 'assets/products/makeup.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 8,
    name: 'Mobile',
    stars: 1,
    image: 'assets/products/mobile.jpeg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 9,
    name: 'Shoe',
    stars: 1,
    image: 'assets/products/shoes.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 10,
    name: 'Smartwatch',
    stars: 1,
    image: 'assets/products/smartwatch.jpeg',
    description: 'abc',
    price: 100,
  ),
];
List<Products> userProductsList = [
  Products(
    id: 1,
    name: 'Bag',
    stars: 1,
    image: 'assets/products/bag.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 2,
    name: 'Blender',
    stars: 1,
    image: 'assets/products/blender.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 3,
    name: 'Camera',
    stars: 1,
    image: 'assets/products/camera1.png',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 4,
    name: 'Wireless',
    stars: 1,
    image: 'assets/products/wireless.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 5,
    name: 'Watch',
    stars: 1,
    image: 'assets/products/watch2.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 6,
    name: 'Headphone',
    stars: 1,
    image: 'assets/products/Headphone.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 7,
    name: 'Makeup',
    stars: 1,
    image: 'assets/products/makeup.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 8,
    name: 'Mobile',
    stars: 1,
    image: 'assets/products/mobile.jpeg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 9,
    name: 'Shoe',
    stars: 1,
    image: 'assets/products/shoes.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 10,
    name: 'Smartwatch',
    stars: 1,
    image: 'assets/products/smartwatch.jpeg',
    description: 'abc',
    price: 100,
  ),
];
List<Products> topRatedSellerList = [
  Products(
    id: 1,
    name: 'Bag',
    stars: 1,
    image: 'assets/products/bag.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 2,
    name: 'Blender',
    stars: 1,
    image: 'assets/products/blender.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 3,
    name: 'Camera',
    stars: 1,
    image: 'assets/products/camera1.png',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 4,
    name: 'Wireless',
    stars: 1,
    image: 'assets/products/wireless.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 5,
    name: 'Watch',
    stars: 1,
    image: 'assets/products/watch2.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 6,
    name: 'Headphone',
    stars: 1,
    image: 'assets/products/Headphone.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 7,
    name: 'Makeup',
    stars: 1,
    image: 'assets/products/makeup.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 8,
    name: 'Mobile',
    stars: 1,
    image: 'assets/products/mobile.jpeg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 9,
    name: 'Shoe',
    stars: 1,
    image: 'assets/products/shoes.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 10,
    name: 'Smartwatch',
    stars: 1,
    image: 'assets/products/smartwatch.jpeg',
    description: 'abc',
    price: 100,
  ),
];
List<Products> topProductsList = [
  Products(
    id: 1,
    name: 'Bag',
    stars: 1,
    image: 'assets/products/bag.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 2,
    name: 'Blender',
    stars: 1,
    image: 'assets/products/blender.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 3,
    name: 'Camera',
    stars: 1,
    image: 'assets/products/camera1.png',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 4,
    name: 'Wireless',
    stars: 1,
    image: 'assets/products/wireless.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 5,
    name: 'Watch',
    stars: 1,
    image: 'assets/products/watch2.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 6,
    name: 'Headphone',
    stars: 1,
    image: 'assets/products/Headphone.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 7,
    name: 'Makeup',
    stars: 1,
    image: 'assets/products/makeup.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 8,
    name: 'Mobile',
    stars: 1,
    image: 'assets/products/mobile.jpeg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 9,
    name: 'Shoe',
    stars: 1,
    image: 'assets/products/shoes.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 10,
    name: 'Smartwatch',
    stars: 1,
    image: 'assets/products/smartwatch.jpeg',
    description: 'abc',
    price: 100,
  ),
];
List<Products> bagsList = [
  Products(
    id: 1,
    name: 'Bag',
    stars: 1,
    image: 'assets/products/bag.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 2,
    name: 'Blender',
    stars: 1,
    image: 'assets/products/blender.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 3,
    name: 'Camera',
    stars: 1,
    image: 'assets/products/camera1.png',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 4,
    name: 'Wireless',
    stars: 1,
    image: 'assets/products/wireless.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 5,
    name: 'Watch',
    stars: 1,
    image: 'assets/products/watch2.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 6,
    name: 'Headphone',
    stars: 1,
    image: 'assets/products/Headphone.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 7,
    name: 'Makeup',
    stars: 1,
    image: 'assets/products/makeup.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 8,
    name: 'Mobile',
    stars: 1,
    image: 'assets/products/mobile.jpeg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 9,
    name: 'Shoe',
    stars: 1,
    image: 'assets/products/shoes.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 10,
    name: 'Smartwatch',
    stars: 1,
    image: 'assets/products/smartwatch.jpeg',
    description: 'abc',
    price: 100,
  ),
];
List<Products> juicersList = [
  Products(
    id: 1,
    name: 'Bag',
    stars: 1,
    image: 'assets/products/bag.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 2,
    name: 'Blender',
    stars: 1,
    image: 'assets/products/blender.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 3,
    name: 'Camera',
    stars: 1,
    image: 'assets/products/camera1.png',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 4,
    name: 'Wireless',
    stars: 1,
    image: 'assets/products/wireless.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 5,
    name: 'Watch',
    stars: 1,
    image: 'assets/products/watch2.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 6,
    name: 'Headphone',
    stars: 1,
    image: 'assets/products/Headphone.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 7,
    name: 'Makeup',
    stars: 1,
    image: 'assets/products/makeup.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 8,
    name: 'Mobile',
    stars: 1,
    image: 'assets/products/mobile.jpeg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 9,
    name: 'Shoe',
    stars: 1,
    image: 'assets/products/shoes.jpg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 10,
    name: 'Smartwatch',
    stars: 1,
    image: 'assets/products/smartwatch.jpeg',
    description: 'abc',
    price: 100,
  ),
];
List<Products> homeBannersList = [
  Products(
    id: 1,
    name: 'Bag',
    stars: 1,
    image: 'assets/banners/banner.jpeg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 2,
    name: 'Blender',
    stars: 1,
    image: 'assets/banners/banner2.jpeg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 3,
    name: 'Camera',
    stars: 1,
    image: 'assets/banners/banner3.jpeg',
    description: 'abc',
    price: 100,
  ),
  Products(
    id: 3,
    name: 'Camera',
    stars: 1,
    image: 'assets/banners/banner3.jpeg',
    description: 'abc',
    price: 100,
  ),
];
